---
# tasks file for packages

- name: install npm package
  package:
    name: "{{ packages }}"
    state: present
  become: yes

- name: install npm modules
  npm:
    name: "{{ item }}"
    state: present
    path: "{{ npm_path }}"
    global: no
  become: no
  with_items: "{{ npm_packages }}"
