---
# defaults file for packages

uninstall_packages: yes
install_prereq: yes
install_rpmfusion: yes
install_base: yes
install_build: yes
install_net: yes
install_tools: yes
install_clients: yes
install_devel: yes
install_gui: yes
install_desktop: yes
install_latex: yes
install_google: yes
update_packages: yes
