---
# Run lynis scan

- name: run a lynis scan      # noqa 301
  command: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_rht-ccp --results-arf /tmp/arf.xml --report /tmp/report.html /usr/share/xml/scap/ssg/content/ssg-centos7-ds.xml    # noqa 204
  creates: /tmp/report.html
  become: yes

- name: generate ansible fix    # noqa 301
  command: oscap xccdf generate fix --fix-type ansible --result-id xccdf_org.ssgproject.content_profile_rht-ccp --output /tmp/scap-playbook-result.yml /tmp/arf.xml     # noqa 204
  become: yes
